
with open("data_input.txt", "r") as myFile:
    a = [line.strip() for line in myFile.readlines()]  # Lưu trữ từng dòng vào danh sách a

# Ghi kết quả vào file alpha_1.txt
with open("alpha.txt", "w") as output_file:
    for i in range(len(a)):  # Lặp qua từng phần tử trong danh sách a
        output_file.write(f"ts_quantile({a[i]},30,driver=\"gaussian\")\n")
        output_file.write(f"ts_quantile({a[i]},30,driver=\"cauchy\")\n")
        output_file.write(f"quantile({a[i]},driver=uniform,sigma=1.0)\n")
        output_file.write(f"quantile({a[i]},driver=cauchy,sigma=1.0)\n")
        output_file.write(f"hump({a[i]},hump=0.0001)\n")
        output_file.write(f"hump({a[i]},hump=0.0005)\n")
        output_file.write(f"hump({a[i]},hump=0.001)\n")
        output_file.write(f"signed_power({a[i]},1.5)\n")
        output_file.write(f"signed_power({a[i]},2.5)\n")
        output_file.write(f"signed_power({a[i]},0.5)\n")
        output_file.write(f"signed_power({a[i]},0.1)\n")
        output_file.write(f"((ceiling({a[i]})))\n")
        output_file.write(f"((exp({a[i]})))\n")
        output_file.write(f"((floor({a[i]})))\n")
        output_file.write(f"((fraction({a[i]})))\n")
        output_file.write(f"(-(inverse({a[i]})))\n")
        output_file.write(f"((log({a[i]})))\n")
        output_file.write(f"((log_diff({a[i]})))\n")
        output_file.write(f"((s_log_1p({a[i]})))\n")
        output_file.write(f"(-(arc_cos(scale({a[i]}))))\n")
        output_file.write(f"((arc_sin(scale({a[i]}))))\n")
        output_file.write(f"((arc_tan({a[i]})))\n")
        output_file.write(f"((pasteurize({a[i]})))\n")
        output_file.write(f"((sigmoid({a[i]})))\n")
        output_file.write(f"((tanh({a[i]})))\n")
        output_file.write(f"((normalize({a[i]})))\n")
        output_file.write(f"((rank({a[i]})))\n")
        output_file.write(f"((zscore({a[i]})))\n")
        output_file.write(f"((winsorize({a[i]},std=2)))\n")
        output_file.write(f"((vector_neut({a[i]},ts_delta({a[i]},250))))\n")
        output_file.write(f"((vector_proj({a[i]},ts_delta({a[i]},250))))\n")
        output_file.write(f"((days_from_last_change({a[i]})))\n")
        output_file.write(f"((-days_from_last_change({a[i]})))\n")
        output_file.write(f"((ts_weighted_decay({a[i]},k=0.5)))\n")
        output_file.write(f"((hump({a[i]},hump=0.01)))\n")
        output_file.write(f"((hump({a[i]},hump=0.001)))\n")
        output_file.write(f"((hump({a[i]},hump=0.005)))\n")
        output_file.write(f"((hump_decay({a[i]},p=0)))\n")
        output_file.write(f"((inst_tvr({a[i]},150)))\n")
        output_file.write(f"((jump_decay({a[i]},120,sensitivity=0.5,force=0.1)))\n")
        output_file.write(f"((last_diff_value({a[i]},150)))\n")
        output_file.write(f"((ts_arg_max({a[i]},150)))\n")
        output_file.write(f"((ts_arg_min({a[i]},150)))\n")
        output_file.write(f"((ts_av_diff({a[i]},150)))\n")
        output_file.write(f"((ts_decay_exp_window({a[i]},150,factor=f)))\n")
        output_file.write(f"((ts_delay({a[i]},150)))\n")
        output_file.write(f"((ts_delta({a[i]},150)))\n")
        output_file.write(f"((ts_ir({a[i]},150)))\n")
        output_file.write(f"((ts_kurtosis({a[i]},150)))\n")
        output_file.write(f"((ts_max({a[i]},150)))\n")
        output_file.write(f"((ts_max_diff({a[i]},150)))\n")
        output_file.write(f"((ts_mean({a[i]},150)))\n")
        output_file.write(f"((ts_median({a[i]},120)))\n")
        output_file.write(f"((ts_min({a[i]},150)))\n")
        output_file.write(f"((ts_min_diff({a[i]},150)))\n")
        output_file.write(f"((-ts_min_max_cps({a[i]},150,f=2)))\n")
        output_file.write(f"((ts_min_max_diff({a[i]},32,f=0.5)))\n")
        output_file.write(f"((ts_moment({a[i]},150,k=0)))\n")
        output_file.write(f"((ts_rank({a[i]},150)))\n")
        output_file.write(f"((ts_returns({a[i]},150)))\n")
        output_file.write(f"((ts_scale({a[i]},150)))\n")
        output_file.write(f"((ts_skewness({a[i]},150)))\n")
        output_file.write(f"((ts_std_dev({a[i]},150)))\n")
        output_file.write(f"((ts_zscore({a[i]},250)))\n")
        output_file.write(f"((ts_entropy({a[i]},250)))\n")
        output_file.write(f"((inst_tvr({a[i]},50)))\n")
        output_file.write(f"((jump_decay({a[i]},20,sensitivity=0.5,force=0.1)))\n")
        output_file.write(f"((last_diff_value({a[i]},50)))\n")
        output_file.write(f"((ts_arg_max({a[i]},50)))\n")
        output_file.write(f"((ts_arg_min({a[i]},50)))\n")
        output_file.write(f"((ts_av_diff({a[i]},50)))\n")
        output_file.write(f"((ts_decay_exp_window({a[i]},50,factor=f)))\n")
        output_file.write(f"((ts_delay({a[i]},50)))\n")
        output_file.write(f"((ts_delta({a[i]},50)))\n")
        output_file.write(f"((ts_ir({a[i]},50)))\n")
        output_file.write(f"((ts_kurtosis({a[i]},50)))\n")
        output_file.write(f"((ts_max({a[i]},50)))\n")
        output_file.write(f"((ts_max_diff({a[i]},50)))\n")
        output_file.write(f"((ts_mean({a[i]},50)))\n")
        output_file.write(f"((ts_median({a[i]},50)))\n")
        output_file.write(f"((ts_min({a[i]},50)))\n")
        output_file.write(f"((ts_min_diff({a[i]},50)))\n")
        output_file.write(f"((-ts_min_max_cps({a[i]},50,f=2)))\n")
        output_file.write(f"((ts_min_max_diff({a[i]},d,f=0.5)))\n")
        output_file.write(f"((ts_moment({a[i]},50,k=0)))\n")
        output_file.write(f"((ts_rank({a[i]},50)))\n")
        output_file.write(f"((ts_returns({a[i]},50)))\n")
        output_file.write(f"((ts_scale({a[i]},50)))\n")
        output_file.write(f"((ts_skewness({a[i]},50)))\n")
        output_file.write(f"((ts_std_dev({a[i]},50)))\n")
        output_file.write(f"((ts_zscore({a[i]},50)))\n")
        output_file.write(f"((ts_entropy({a[i]},50)))\n")
        output_file.write(f"(regression_neut({a[i]}, group_mean({a[i]}, 1, industry)))\n")
        output_file.write(f"(regression_proj({a[i]}, group_mean({a[i]}, 1, industry)))\n")
        output_file.write(f"(group_zscore({a[i]}, 1))\n")
        output_file.write(f"(group_max({a[i]}, 1))\n")
        output_file.write(f"(group_min({a[i]}, 1))\n")
        output_file.write(f"(group_normalize({a[i]}, 1))\n")
        output_file.write(f"(group_rank({a[i]}, 1))\n")
        output_file.write(f"(group_scale({a[i]}, 1))\n")
        output_file.write(f"(group_std_dev({a[i]}, 1))\n")
        output_file.write(f"(group_sum({a[i]}, 1))\n")
print("Chương trình đã chạy xong! Dữ liệu đã được ghi vào alpha.txt")
